---
name: CI

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions: read-all

concurrency:
  group: "${{ github.head_ref || github.ref }}-${{ github.workflow }}"
  cancel-in-progress: true

jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4.0.0
        with:
          persist-credentials: false
      - name: Install Poetry
        run: pipx install poetry==1.8.3

      - name: Set up Python
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version-file: .python-version
          cache: poetry

      - name: Install dependencies
        run: make install-dev

      - name: Lint Python
        run: make lint

      - name: Test
        run: make test
